language: shell

os: osx
osx_image: xcode11.3
env: BINTRAY_VERSION=latest

jobs:
  include:
    - stage: "Precondition"
      name: "Check for updated formulae"
      script: source .travis/00-precondition.sh
    - stage: "Preparation"
      name: "Prepare for building"
      script: .travis/01-preparation.sh
    - stage: "Setup"
      name: "Setup workspace"
      script: .travis/02-setup.sh
    - stage: "Build"
      name: "Build formula"
      script: .travis/03-build.sh
    - stage: "Package"
      name: "Package formula"
      script: .travis/04-package.sh
    - stage: "Deploy"
      name: "Deploy to tap"
      script: ./deploy-tap.sh ${TARGET_FORMULA}

stages:
  - Precondition
  - name: Preparation
    if: env(DO_BUILD) = 1
  - name: Setup
    if: env(DO_BUILD) = 1
  - name: Build
    if: env(DO_BUILD) = 1
  - name: Package
    if: env(DO_BUILD) = 1
  - name: Deploy
    if: (env(DO_BUILD) = 1) AND (branch = master)

before_cache:
  - brew update
  - brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/pip"
  - "$HOME/Library/Caches/Homebrew"
