language: shell

os: osx
osx_image: xcode11.3
env: BINTRAY_VERSION=latest

install:
  - brew update
  - brew tap hguandl/custom
  - export TARGET_FORMULA=$(echo ${TRAVIS_COMMIT_MESSAGE} | cut -f 1 -d ":")

script:
  - travis_wait 120 brew install hguandl/custom/${TARGET_FORMULA} --build-bottle

before_cache:
  - brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/pip"
  - "$HOME/Library/Caches/Homebrew"

before_deploy:
  - git config user.name ${GITHUB_USERNAME}
  - git config user.email ${GITHUB_EMAIL}
  - echo "machine github.com\n  login ${GITHUB_USERNAME}\n  password ${GITHUB_TOKEN}" >> ~/.netrc
  - echo "machine github.com\n  login ${BINTRAY_USERNAME}\n  password ${BINTRAY_KEY}" >> ~/.netrc
  - brew bottle --json ros --root-url ${BOTTLE_ROOT_URL}
  - brew bottle --merge --write $(ls ${TARGET_FORMULA}*bottle*.json)
  - pip3 install requests

deploy:
  - provider: script
    cleanup: false
    script: python3 upload.py ${TARGET_FORMULA}
    on:
      branch: master
    edge: true

  - provider: script
    cleanup: false
    script: ./deploy-push.sh
    on:
      branch: master
    edge: true
