language: shell

os: osx
osx_image: xcode11.3
env: BINTRAY_VERSION=latest

stages:
  - precondition
  - name: before_install
    if: env(DO_BUILD) = 1
  - name: install
    if: env(DO_BUILD) = 1
  - name: script
    if: env(DO_BUILD) = 1
  - name: before_deploy
    if: env(DO_BUILD) = 1
  - name: deploy
    if: env(DO_BUILD) = 1
  - name: after_deploy
    if: env(DO_BUILD) = 1

precondition:
  - export TARGET_FORMULA=$(echo ${TRAVIS_COMMIT_MESSAGE} | cut -f 1 -d ":")
  - ./precondition.sh
  - if [ -e .DO_BUILD ]; then; export DO_BUILD=1; fi

before_install:
  - git config --global user.name ${GITHUB_USERNAME}
  - git config --global user.email ${GITHUB_EMAIL}
  - echo -e "machine github.com\n  login ${GITHUB_USERNAME}\n  password ${GITHUB_TOKEN}" > ~/.netrc
  - echo -e "machine api.bintray.com\n  login ${BINTRAY_USERNAME}\n  password ${BINTRAY_KEY}" >> ~/.netrc

install:
  - brew update
  - brew upgrade
  - brew tap hguandl/custom

script:
  - travis_wait 120 brew install hguandl/custom/${TARGET_FORMULA} --build-bottle

before_cache:
  - brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/pip"
  - "$HOME/Library/Caches/Homebrew"

before_deploy:
  - brew update
  - brew bottle --json ${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL} || brew bottle --skip-relocation --json ${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL}
  - brew bottle --merge --write $(ls ${TARGET_FORMULA}*bottle*.json)
  - pip3 install requests

deploy:
  - provider: script
    cleanup: false
    script: ./deploy-tap.sh ${TARGET_FORMULA}
    on:
      branch: master
      condition: $DO_DEPLOYMENT = 1
    edge: true

after_deploy:
  - brew update
