language: shell

os: osx
osx_image: xcode11.3
env: BINTRAY_VERSION=latest

install:
  - brew update
  - brew upgrade
  - brew tap hguandl/custom
  - export TARGET_FORMULA=$(echo ${TRAVIS_COMMIT_MESSAGE} | cut -f 1 -d ":")

script:
  - travis_wait 120 ./build-bottle.sh

before_cache:
  - git config --global user.name ${GITHUB_USERNAME}
  - git config --global user.email ${GITHUB_EMAIL}
  - brew cleanup

cache:
  directories:
  - "/usr/local/Homebrew"
  - "$HOME/Library/Caches/pip"
  - "$HOME/Library/Caches/Homebrew"

before_deploy:
  - echo "machine github.com\n  login ${GITHUB_USERNAME}\n  password ${GITHUB_TOKEN}" >> ~/.netrc
  - echo "machine api.bintray.com\n  login ${BINTRAY_USERNAME}\n  password ${BINTRAY_KEY}" >> ~/.netrc
  - brew update
  - brew bottle --json ${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL} || brew bottle --skip-relocation --json ${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL}
  - brew bottle --merge --write $(ls ${TARGET_FORMULA}*bottle*.json)
  - pip3 install requests

deploy:
  - provider: script
    cleanup: false
    script: ./deploy-tap.sh ${TARGET_FORMULA}
    on:
      branch: master
    edge: true

after_deploy:
  - brew update
