# This is a basic workflow to help you get started with Actions

name: Build bottles

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ ci ]

env:
  HOMEBREW_TAP: hguandl/custom
  BOTTLE_ROOT_URL: https://dl.bintray.com/hguandl/homebrew-custom/bottles


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        source ./precondition.sh
        echo "::set-env name=TARGET_FORMULA::$TARGET_FORMULA"
        git config --global user.name ${GITHUB_USERNAME}
        git config --global user.email ${GITHUB_EMAIL}
        echo -e "machine github.com\n  login ${GITHUB_USERNAME}\n  password ${GITHUB_TOKEN}" > ~/.netrc
        echo -e "machine api.bintray.com\n  login ${BINTRAY_USERNAME}\n  password ${BINTRAY_KEY}" >> ~/.netrc
      env:
        GITHUB_USERNAME: hguandl-bot
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        BINTRAY_USERNAME: hguandl
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

    # Runs a set of commands using the runners shell
    - name: Install
      run: |
        brew untap ${HOMEBREW_TAP} || true
        brew update
        brew cask install xquartz || true
        brew tap ${HOMEBREW_TAP}
        pushd $(brew --repository ${HOMEBREW_TAP})
        git fetch origin ci
        git merge origin/ci --ff-only
        popd
        brew tap ${HOMEBREW_TAP}
        pip3 install requests

    - name: Build
      run: brew install ${HOMEBREW_TAP}/${TARGET_FORMULA} --build-bottle

    - name: Package
      run: |
        brew bottle --json ${HOMEBREW_TAP}/${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL} || brew bottle --skip-relocation --json ${TARGET_FORMULA} --root-url ${BOTTLE_ROOT_URL}
        brew bottle --merge --write $(ls ${TARGET_FORMULA}*bottle*.json)

    - name: Upload
      run: ./deploy-tap.sh ${TARGET_FORMULA}
